module: "uvvis"
params:
  baseline:
    method: "asls"
    lam: 100000.0
    p: 0.01
    niter: 10
  join:
    enabled: true
    window: 3
    threshold: 0.2
    windows:
      helios:
        - min_nm: 340.0
          max_nm: 360.0
          spikes: 1
  stitch:
    enabled: false
    shoulder_points: 5
    method: linear
    fallback_policy: preserve
    windows: []
  qc:
    quiet_window:
      min: 850.0
      max: 900.0
  despike:
    enabled: false
    window: 5
    zscore: 5.0
  smoothing:
    enabled: false
    window: 15
    polyorder: 3
version: "0.1.0"
